name: Generate GitHub Readme Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats Card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: stats
          options: 'username=raoopriyanka&show_icons=true&theme=tokyonight&include_all_commits=true&count_private=true'
          path: profile/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages Card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: top-langs
          options: 'username=raoopriyanka&layout=compact&theme=tokyonight&hide_border=false'
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push SVGs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update GitHub Stats SVGs" || exit 0
          git push
